library/books/forms.py
from datetime import datetime

from flask_wtf import FlaskForm
from wtforms import BooleanField
from wtforms import DateField
from wtforms import IntegerField
from wtforms import SearchField
from wtforms import SelectField
from wtforms import StringField
from wtforms import SubmitField
from wtforms.validators import DataRequired
from wtforms.validators import Length
from wtforms.validators import ValidationError

from library.books.models import Book
from library.books.models import BookGenre
from library.books.models import BookOrders

ORDER_CHOICES = [(x.value, x.value) for x in BookOrders]  # type: ignore
GENRE_CHOICES = [("", "Select a genre")] + [(x.value, x.value) for x in BookGenre]  # type: ignore


class FilterBooksForm(FlaskForm):
    title = SearchField("Title")
    genre = SelectField("Genre", choices=GENRE_CHOICES, default="")  # type: ignore
    author = SearchField("Author")
    isbn = SearchField("ISBN")
    available = BooleanField("Only available", default=False)
    order_by = SelectField("Order by", choices=ORDER_CHOICES, default="none")

    submit = SubmitField("Filter")


class RentBookForm(FlaskForm):
    email_or_phone_number = SearchField("Email or phone number", validators=[DataRequired()])
    submit = SubmitField("Rent")


class AddBookForm(FlaskForm):
    title = StringField(
        "Title",
        validators=[DataRequired(), Length(max=100, message="Title too long")],
        default="Witcher",
    )
    authors = StringField(
        "Authors",
        validators=[DataRequired(), Length(max=100, message="Authors too long")],
        default="Steve Smith",
    )
    topic = StringField(
        "Topic",
        validators=[DataRequired(), Length(max=100, message="Topic too long")],
        default="Fighting",
    )
    genre = SelectField("Genre", choices=GENRE_CHOICES, default="Fantasy")  # type: ignore

    publication_date = DateField(
        "Publication date (YYYY-MM-DD)", validators=[DataRequired()], default=datetime.now()
    )
    publisher = StringField(
        "Publisher",
        validators=[DataRequired(), Length(max=100, message="Publisher too long")],
        default="Book publisher",
    )
    description = StringField(
        "Description",
        validators=[DataRequired(), Length(max=100, message="Description too long")],
        default="Nice book",
    )
    isbn = StringField(
        "ISBN",
        validators=[DataRequired(), Length(max=100, message="ISBN not valid")],
        default="1234567890",
    )
    pages = IntegerField("Pages", validators=[DataRequired()], default=345)
    stock = IntegerField("Stock", validators=[DataRequired()], default=5)
    submit = SubmitField("Add")


class AddReviewForm(FlaskForm):
    rating = SelectField(
        "Rating", validators=[DataRequired()], choices=[(x, x) for x in range(1, 6)]
    )
    comment = StringField("Comment", validators=[DataRequired()])
    submit = SubmitField("Add")


class ModifyBookForm(FlaskForm):
    def __init__(self, book_id, override=False, *args, **kwargs):
        super(ModifyBookForm, self).__init__(*args, **kwargs)
        self.book_id = book_id
        if override:
            self.fetch_book_data()

    def fetch_book_data(self):
        book = Book.get(self.book_id).run()
        self.title.data = book.title
        self.authors.data = ",".join(book.authors)
        self.topic.data = book.topic
        self.genre.data = book.genre
        self.publication_date.data = book.publication_date
        self.publisher.data = book.publisher
        self.description.data = book.description
        self.isbn.data = book.isbn
        self.pages.data = book.pages
        self.stock.data = book.stock
        self.initial_stock.data = book.initial_stock

    title = StringField(
        "Title",
        validators=[DataRequired(), Length(max=100, message="Title too long")],
    )
    authors = StringField(
        "Authors",
        validators=[DataRequired(), Length(max=100, message="Authors too long")],
    )
    topic = StringField(
        "Topic",
        validators=[DataRequired(), Length(max=100, message="Topic too long")],
    )
    genre = SelectField("Genre", choices=GENRE_CHOICES)  # type: ignore

    publication_date = DateField(
        "Publication date (YYYY-MM-DD)",
        validators=[DataRequired()],
    )
    publisher = StringField(
        "Publisher",
        validators=[DataRequired(), Length(max=100, message="Publisher too long")],
    )
    description = StringField(
        "Description",
        validators=[DataRequired(), Length(max=1000, message="Description too long")],
    )
    isbn = StringField(
        "ISBN",
        validators=[DataRequired(), Length(max=100, message="ISBN not valid")],
    )
    pages = IntegerField("Pages", validators=[DataRequired()])
    stock = IntegerField("Stock", validators=[DataRequired()])
    initial_stock = IntegerField("Initial Stock", validators=[DataRequired()])
    submit = SubmitField("Save")

    def validate_stock(self, stock):
        print("zbita")
        print(stock.data, self.initial_stock.data)
        if stock.data > self.initial_stock.data:
            print("dupa")
            raise ValidationError("Stock cannot be greater than initial stock")

library/books/routes.py
import datetime
import math
import random
from decimal import Decimal

from bunnet import PydanticObjectId
from faker import Faker
from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required

from library import mongo_client
from library.auth.decorators import admin_role_required
from library.auth.models import User
from library.books.forms import AddBookForm
from library.books.forms import AddReviewForm
from library.books.forms import FilterBooksForm
from library.books.forms import ModifyBookForm
from library.books.forms import RentBookForm
from library.books.models import Book
from library.books.models import Rent
from library.books.models import Review

books = Blueprint("books", __name__)

faker = Faker()

faker = Faker()


@books.route("/books", methods=["GET"])
@login_required
def list_books():
    page = request.args.get("page", 1, type=int)
    page_size = request.args.get("page_size", 24, type=int)

    filters = {
        "title": request.args.get("title", None),
        "genre": request.args.get("genre", None),
        "author": request.args.get("author", None),
        "available": request.args.get("available", None, type=bool),
        "isbn": request.args.get("isbn", None),
        "order_by": request.args.get("order_by", None),
    }
    form = FilterBooksForm(**filters)
    filters_query_string = "&".join([f"{k}={v}" for k, v in filters.items() if v])

    query = Book.filter(**filters)
    books_ = query.skip((page - 1) * page_size).limit(page_size).run()
    total = query.count()

    pagination = {
        "page": page,
        "page_size": page_size,
        "total": total,
        "total_pages": math.ceil(total / page_size),
    }

    return render_template(
        "books/list_books.html",
        form=form,
        books=books_,
        pagination=pagination,
        filters_query_string=filters_query_string,
    )


@books.route("/books/<book_id>", methods=["GET", "POST"])
@login_required
def book_detail(book_id):
    book = Book.get(book_id).run()
    reviews = Review.find(Review.book_id == PydanticObjectId(book_id), fetch_links=True).run()

    already_rented = bool(
        Rent.find_one(
            Rent.book.id == PydanticObjectId(book_id),
            Rent.user.id == PydanticObjectId(current_user.id),
        ).run()
    )

    review_added = bool(
        Review.find_one(
            Review.book_id == PydanticObjectId(book_id),
            Review.user.id == PydanticObjectId(current_user.id),
        ).run()
    )

    form = RentBookForm()
    if request.method == "POST":
        if not current_user.is_admin:
            abort(403)

        user = (
            User.find_one({"email": form.email_or_phone_number.data}).run()
            or User.find_one({"email": form.email_or_phone_number.data}).run()
        )

        if not user:
            flash("User not found", "danger")
            return redirect(url_for("books.book_detail", book_id=book_id))

        return redirect(url_for("books.rent_book", book_id=book_id, user_id=str(user.id)))

    return render_template(
        "books/book_detail.html",
        book=book,
        form=form,
        reviews=reviews,
        already_rented=already_rented,
        review_added=review_added,
    )


@books.route("/books/<book_id>/rent/<user_id>", methods=["GET"])
@login_required
@admin_role_required
def rent_book(book_id, user_id):
    user = User.get(user_id).run()
    book = Book.get(book_id).run()
    rent = Rent.find_one(
        Rent.book.id == PydanticObjectId(book_id),
        Rent.user.id == PydanticObjectId(user_id),
        Rent.return_date == None,  # noqa
    ).run()

    if not book or not user:
        raise abort(404)

    if rent:
        flash("Book already rented", "danger")
        return redirect(book.detail_url)

    if not book.is_available:
        raise abort(403)

    with mongo_client.start_session() as session, session.start_transaction():
        book.stock -= 1
        book.save(session=session)
        rent = Rent(book=book, user=user)
        rent.save(session=session)

    flash("Book rented successfully", "success")
    return redirect(url_for("auth.user_details", user_id=user_id))


@books.route("/books/<book_id>/return/<user_id>", methods=["GET"])
@login_required
@admin_role_required
def return_book(book_id, user_id):
    rent = Rent.find_one(
        Rent.book.id == PydanticObjectId(book_id),
        Rent.user.id == PydanticObjectId(user_id),
        Rent.return_date == None,  # noqa
    ).run()

    if not rent:
        raise abort(404)

    with mongo_client.start_session() as session, session.start_transaction():
        book = Book.get(book_id).run()
        book.stock += 1
        book.save(session=session)
        rent.return_date = datetime.date.today().isoformat()
        rent.save(session=session)

    flash("Book returned successfully", "success")
    return redirect(url_for("auth.user_details", user_id=user_id))


@books.route("/books/remove/<book_id>", methods=["GET"])
@login_required
@admin_role_required
def remove_book(book_id):
    try:
        book = Book.get(book_id).run()
        book.delete()
        flash("Book has been removed", "success")
    except Exception:
        flash("Removing error", "error")

    return redirect(url_for("books.list_books"))


@books.route("/books/add_book", methods=["GET", "POST"])
@login_required
@admin_role_required
def add_book():
    form = AddBookForm()
    if request.method == "POST" and form.validate_on_submit():
        book = Book(
            title=form.title.data,
            authors=form.authors.data.split(","),
            topic=form.topic.data,
            genre=form.genre.data,
            publication_date=form.publication_date.data,
            publisher=form.publisher.data,
            description=form.description.data,
            isbn=form.isbn.data,
            pages=form.pages.data,
            stock=form.stock.data,
            initial_stock=form.stock.data,
            images_urls=[faker.image_url() for _ in range(random.randint(1, 3))],
        )
        book.authors = book.authors[0].split(",")
        book.save()
        flash("New book has been added", "success")
        return redirect(url_for("books.list_books"))

    return render_template("books/add_book.html", form=form)


@books.route("/returns/overdue", methods=["GET"])
@login_required
@admin_role_required
def overdue_returns():
    page = request.args.get("page", 1, type=int)
    page_size = request.args.get("page_size", 24, type=int)

    query = Rent.get_overdue().find(fetch_links=True).sort(Rent.due_date)
    rents = query.skip((page - 1) * page_size).limit(page_size).run()
    total = query.count()

    pagination = {
        "page": page,
        "page_size": page_size,
        "total": total,
        "total_pages": math.ceil(total / page_size),
    }

    return render_template("books/overdue_returns.html", rents=rents, pagination=pagination)


@books.route("/books/<book_id>/add_review", methods=["GET", "POST"])
@login_required
def add_review(book_id):
    book = Book.get(book_id).run()

    review = Review.find_one(
        Review.book_id == PydanticObjectId(book_id),
        Review.user.id == PydanticObjectId(current_user.id),
    ).run()

    rent = Rent.find_one(
        Review.book_id == PydanticObjectId(book_id),
        Review.user.id == PydanticObjectId(current_user.id),
    )

    if not book:
        abort(404)

    if review:
        abort(403)

    if not rent:
        abort(403)

    form = AddReviewForm()
    if request.method == "POST" and form.validate_on_submit():
        rating = Decimal(form.rating.data)
        with mongo_client.start_session() as session, session.start_transaction():
            review = Review(
                book_id=book_id,
                user=current_user,
                rating=rating,
                comment=form.comment.data,
            )
            book.add_review(rating)
            book.save(session=session)
            review.save(session=session)

        flash("New review has been added", "success")
        return redirect(url_for("books.book_detail", book_id=book_id))

    return render_template("books/add_review.html", form=form, book=book)


@books.route("/books/modify/<book_id>", methods=["GET", "POST"])
@login_required
@admin_role_required
def modify_book(book_id):
    form = ModifyBookForm(book_id, override=request.method == "GET")
    if request.method == "POST" and form.validate_on_submit():
        book = Book.get(book_id).run()
        book.title = form.title.data
        book.authors = form.authors.data.split(",")
        book.topic = form.topic.data
        book.genre = form.genre.data
        book.publication_date = form.publication_date.data
        book.publisher = form.publisher.data
        book.description = form.description.data
        book.isbn = form.isbn.data
        book.pages = form.pages.data
        book.stock = form.stock.data
        book.initial_stock = form.stock.data
        book.images_urls = [faker.image_url() for _ in range(random.randint(1, 3))]
        book.initial_stock = form.initial_stock.data

        book.save()
        flash("Book has been modified", "success")
        return redirect(url_for("books.list_books"))

    return render_template("books/add_book.html", form=form)

library/templates/books/add_book.html
{% from "_form_macros.html" import render_field %}

{% extends "base.html" %}
{% block title %}
Add book
{% endblock %}

{% block content %}
<h1>Add book</h1>

<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
     {{ render_field(form, 'title') }}
     {{ render_field(form, 'authors') }}
     {{ render_field(form, 'topic') }}
     {{ render_field(form, 'genre') }}
     {{ render_field(form, 'publication_date') }}
     {{ render_field(form, 'publisher') }}
     {{ render_field(form, 'description') }}
     {{ render_field(form, 'isbn') }}
     {{ render_field(form, 'pages') }}
     {{ render_field(form, 'stock') }}
     {{ render_field(form, 'initial_stock') }}
    </fieldset>
    <div class="form-group mt-3">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock %}

library/templates/books/add_review.html
{% from "_form_macros.html" import render_field %}
{% extends "base.html" %}

{% block title %}
  Add review for {{ book.title }}
{% endblock %}

{% block content %}
  <h2>Add a review for {{ book.title }}</h2>

  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
     {{ render_field(form, 'rating') }}
     {{ render_field(form, 'comment') }}
    </fieldset>
    <div class="form-group mt-3">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
{% endblock %}

library/templates/books/book_detail.html
{% from "_form_macros.html" import render_field %}

{% extends "base.html" %}

{% block title %}
 {{ book.title }}
{% endblock %}

{% block content %}
<div class="row mt-3">
  <div class="col">
    <!-- Carousel -->
    <div id="bookImagesCarousel" class="carousel slide mt-4" data-bs-ride="carousel">
      <div class="carousel-inner">
        {% for url in book.images_urls %}
          <div class="carousel-item{% if loop.first %} active{% endif %}">
            <img src="{{ url }}" class="d-block w-100 carousel-image" alt="{{ book.title }} image">
          </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#bookImagesCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#bookImagesCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="mt-4">
      <h2>{{ book.title }}</h2>
      <p><strong>Authors:</strong> {{ book.authors|join(', ') }}</p>
      <p><strong>Topic:</strong> {{ book.topic }}</p>
      <p><strong>Genre:</strong> {{ book.genre }}</p>
      <p><strong>Publication date:</strong> {{ book.publication_date.strftime('%Y-%m-%d') }}</p>
      <p><strong>Description:</strong> {{ book.description }}</p>
      <p><strong>Publisher:</strong> {{ book.publisher }}</p>
      <p><strong>ISBN:</strong> {{ book.isbn }}</p>
      <p><strong>Pages:</strong> {{ book.pages }}</p>
      <p><strong>Stock:</strong> {{ book.stock }} (Initial stock: {{ book.initial_stock }})</p>
      <p><strong>Average rating:</strong> {{ book.avg_rating }}</p>
      <p><strong>Number of reviews:</strong> {{ book.review_count }}</p>

      {% if current_user.is_admin %}
        <a href="{{ url_for('books.modify_book', book_id=book.id) }}">
            <button class="btn btn-primary">Make Changes</button>
        </a>
      {% endif %}

      {% if current_user.is_admin %}
        <a href="{{ url_for('books.remove_book', book_id=book.id) }}">
            <button class="btn btn-primary">Remove Book</button>
        </a>
      {% endif %}
    </div>

    {% if book.is_available and current_user.is_admin %}
    <hr>
    <div class="mt-4">
      <form method="POST" action="">
         <fieldset class="form-group">
            {{ render_field(form, 'email_or_phone_number') }}

            <div class="form-group mt-3">
              {{ form.submit(class="btn btn-outline-info") }}
            </div>
         </fieldset>
      </form>
    </div>
    {% endif %}

    <hr>
    {% if reviews %}
      <div>
        <h3>Reviews</h3>
        {% for review in reviews %}
          <div class="card mt-3">
            <div class="card-body">
              <h5 class="card-title mt-1">{{ review.user.full_name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ review.created_at.strftime('%Y-%m-%d') }}</h6>
              <p class="card-text">{{ review.rating }}/5 {{ review.comment }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>
        There are no reviews for this book yet.
      </p>
    {% endif %}

    {% if not current_user.is_admin and already_rented and not review_added %}
      <a href="{{ book.add_review_url }}" class="btn btn-primary"> Add a review</a>
    {% endif %}
  </div>
</div>
{% endblock %}

library/templates/books/list_books.html
{% from "_form_macros.html" import render_field %}
{% from "_pagination.html" import render_pagination %}

{% extends "base.html" %}
{% block content %}
<h1 class="my-3">Book List</h1>
<div class="row">
    <div class="col-3">
        {% if current_user.is_admin %}
        <a href="{{ url_for('books.add_book') }}">
            <button class="btn btn-primary">Add Book</button>
        </a>
        {% endif %}
        <form method="GET" action="">
            <fieldset class="form-group">
              {{ render_field(form, 'title') }}
              {{ render_field(form, 'genre') }}
              {{ render_field(form, 'author') }}
              {{ render_field(form, 'isbn') }}
              {{ render_field(form, 'order_by') }}

              <div class="form-check mt-2">
                  <input class="form-check-input" type="checkbox" value="1" id="available" name="available" {% if form.available.data %}checked{% endif %}>
                  <label class="form-check-label" for="available">
                    {{ form.available.label.text }}
                  </label>
                </div>
            </fieldset>

            <div class="form-group mt-3">
              {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="col-9">
    {% if books %}

    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for book in books %}
        <a href="{{ book.detail_url }}" class="text-reset text-decoration-none">
        <div class="col">
            <div class="card h-100">
                <div class="img-wrapper">
                    <img src="{{ book.images_urls[0] }}" class="card-img-top" alt="{{ book.title }}">
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">Authors: {{ ', '.join(book.authors) }}</p>
                    <p class="card-text">Genre: {{ book.genre }}</p>
                    <p class="card-text">Publication Date: {{ book.publication_date.strftime('%Y-%m-%d')}}</p>
                    <p class="card-text">Pages: {{ book.pages }}</p>
                    <p class="card-text">Availability: {{ book.stock }}/{{ book.initial_stock }}</p>
                </div>
            </div>
        </div>
        </a>
        {% endfor %}
    </div>
    {% else %}
        <h2 class="text-center">There are no books that meet the given criteria.</h2>
    {% endif %}
</div>
</div>

{{ render_pagination(pagination, url_for('books.list_books'), filters_query_string) }}

{% endblock %}

library/templates/books/overdue_returns.html
{% from "_pagination.html" import render_pagination %}
{% extends "base.html" %}

{% block content %}
<h1 class="mt-5 mb-3">Overdue Rents</h1>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th scope="col">Member Name</th>
                <th scope="col">Book Title</th>
                <th scope="col">Rent Due Date</th>
            </tr>
        </thead>
        <tbody>
            {% for rent in rents %}
                <tr>
                    <td><a class="text-decoration-none text-reset" href="{{ rent.user.details_url }}">{{ rent.user.full_name }}</a></td>
                    <td><a class="text-decoration-none text-reset" href="{{ rent.book.detail_url }}">{{ rent.book.title }}</a></td>
                    <td>{{ rent.due_date.strftime('%Y-%m-%d') }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5" class="text-center">No overdue rents found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{{ render_pagination(pagination, url_for('books.overdue_returns'), '')}}
{% endblock %}